### ISSUE TITLE
进程:简介中的一个错误(似乎这部分没人翻译,是机翻的qwq)

### ISSUE THREAD

**Issue by hehelego** [apachecn/uiuc-cs241-notes-zh#4]
[link](http://cs241.apachecn.org/#/docs/15?id=%e8%bf%9b%e7%a8%8b%e5%8a%9f%e8%83%bd%e9%99%90%e5%88%b6%ef%bc%88%e5%a5%96%e9%87%91%ef%bc%89)  

在 `2.进程-进程,第1部分:简介` 中,这个文档最后关于PID的描述中,出现一出翻译问题.

> 进程也可以包含
> - 映射
> - 州
> - 文件描述符
> - 权限

这里对应原文,应当翻译为`状态`而非`州`
> Processes could also contain
>    **Running State** - Whether a process is getting ready, running, stopped, terminated etc.
>    File Descriptors - List of mappings from integers to real devices (files, usb sticks, sockets)
>    Permissions - What user the file is running on and what group the process belongs to. The process can then only do this admissible to the user or group like opening a file that the user has made exclusives. There are tricks to make a program not be the user who started the program i.e. sudo takes a program that a user starts and executes it as root.
>    Arguments - a list of strings that tell your program what parameters to run under
>    Environment List - a list of strings in the form NAME=VALUE that one can modify.

**Comment by wizardforcel** [comment]
请提交PULL REQUESRT谢谢
